### ISSUE TITLE
Algorithm sucks

### ISSUE THREAD

**Issue by gabrielkrell** [gabrielkrell/ECE100LineFollower#2]
Won't do sharp angles.  Think of something else.

**Comment by gabrielkrell** [comment]
New algorithm implemented in commit 7ee4cd3a44802da75185ce35eaa3a0c282f36dde.  Needs to be tested.

**Comment by ghost** [comment]
The degree turn limit is 45 degrees, right?

**Comment by gabrielkrell** [comment]
Yeah, 135° from the current direction. Tripped me up on the first pre-lab

**Comment by gabrielkrell** [comment]
OK, possible algorithm for three sensors:

```
if front sensor
    move fwd
else
    turn in direction of whichever sensor is on or whichever sensor was most recently on until front sensor is on again
```

**Comment by ghost** [comment]
What would happen if the else statement was applied when the robot met a right turn of say, 90 degrees? The robot would move to the direction in which the sensor was recently on. That would happen to be both left and right? I'm not sure if we are meaning "on" as having light actually hit the sensors on the white tape. Or is "on" when no light hits the sensors as a result of the black coating?

**Comment by gabrielkrell** [comment]
I guess that wasn't clear.  Say the robot is going through a 90-degree right turn:
1. The front sensor moves past the turn.  This triggers  
   2.The robot turns in the L/R direction that was most recently "on", which would be the right sensor.  It does this until the front sensor is "on" again, indicating that it's back on the line.

I use "on" to mean "on the line".

Here's a really shitty diagram where the triangle is the robot and the dots are its sensors.  There are very nice animated gifs in the instructable I linked.
![image](https://cloud.githubusercontent.com/assets/11408441/19050686/5441808a-8975-11e6-8e3f-db8804201d37.png)

**Comment by gabrielkrell** [comment]
Well, we switched algorithms to follow the side of the edge instead of stay on the path, so that fixed all of our problems.  See 35e63e2615c0cbe0106cc87dc73c52deb182c132 for original implementation, a81f3392c2dc7bfdf67f7e1b19fb1119747ef131 for final.
