### ISSUE TITLE
Briefing us up on Github

### ISSUE THREAD

**Issue by ghost** [gabrielkrell/ECE100LineFollower#3]
Gabriel,

It's been almost two years since I last used Github and my knowledge of it is a bit rusty. Could you explain the inner workings of it at a later time? I won't take more than 10 minutes of your time.

-Siva

**Comment by gabrielkrell** [comment]
GitHub is an easy way to make + track changes in a codebase.  The easiest way to use it (what i do, tbh) is to download the GitHub Desktop client.  You'll tell it to clone the repository (to make a local copy), then make your changes, and then submit a commit that'll upload those changes and a short description to the repo.  You can also do it through command-line but I'm lazy and haven't learned.

**Comment by gabrielkrell** [comment]
I'm thinking about making another branch for a three-sensor algorithm, but I have a fair amount of work to do, so I can't tonight.  It would probably be best to take advantage of a third sensor (probably by putting one in the front and one on each side).  If you have more questions it'll be faster to reach my via Facebook chat

**Comment by ghost** [comment]
> It would be best to take advantage of a third sensor

That's good to hear. I was thinking more of the same. By increasing the number of inputs we have, we can make the algorithm a bit easy to write down.

**Comment by gabrielkrell** [comment]
Yeah.  It looks like a lot of multi-sensor algorithms use one in the front to see if the path keeps going straight and the others on the side to know which way to turn: http://www.instructables.com/id/Robot-Line-Follower/?ALLSTEPS#step24
