### ISSUE TITLE
Lab report notes

### ISSUE THREAD

**Issue by ghost** [gabrielkrell/ECE100LineFollower#4]
This will be a place where we can come, read, and base our lab report theories on.

**Comment by ghost** [comment]
## Physicality of the robot

The robot needs to be physically sturdy to handle the physical damages it might incur from navigating through the intended terrain. The team members are invited to use this as one of the many supposed constraints/issues they'd face.

**Comment by ghost** [comment]
## Algorithm refining

The team has to account for the different angles in the testing site's white tape. The algorithm has to successfully tackle every single one of the turns on the test site. That way, the team can be sure that they'd have a good test run. Different loops in the code must successfully interact with each other to produce the intended result. The speed, the turn degree, the sensing of the robot leaving the white tape, and the physical integrity of the robot (stuff coming off and we losing the competition because of a frikkin' loose connection!).

**Comment by gabrielkrell** [comment]
Do you want to put this in the wiki instead?  I feel like that might be a better fit

**Comment by ghost** [comment]
Sure. I didn't know of it lol

**Comment by gabrielkrell** [comment]
No prob.
